version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      groups:
          github-actions:
              patterns:
                  - "*"

    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"
      groups:
          python:
              update-types:
                  - "minor"
                  - "patch"
