# Generated by Django 5.2.5 on 2025-08-16 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password Must Contain At Least One Uppercase Letter, One Lowercase Letter, One Digit, and One Special Character', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$'), django.core.validators.MinLengthValidator(limit_value=8, message='Password Must Contain At Least 8 Characters'), django.core.validators.MaxLengthValidator(limit_value=60, message='Password Must Not Exceed 60 Characters')], verbose_name='Password'),
        ),
    ]
