# Generated by Django 5.2.5 on 2025-08-17 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, unique=True, validators=[django.core.validators.EmailValidator(code='invalid_email', message='Invalid Email Address')], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First Name Must Contain Only Letters With No Spaces', regex='^[A-Za-z]+$'), django.core.validators.MaxLengthValidator(limit_value=60, message='First Name Must Not Exceed 60 Characters')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Last Name Must Contain Only Letters With No Spaces', regex='^[A-Za-z]+$'), django.core.validators.MaxLengthValidator(limit_value=60, message='Last Name Must Not Exceed 60 Characters')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username Must Contain Only Alphanumeric Characters With No Spaces', regex='^[A-Za-z0-9]+$'), django.core.validators.MaxLengthValidator(limit_value=60, message='Username Must Not Exceed 60 Characters')], verbose_name='Username'),
        ),
    ]
